theme: minima
title: Learn DevOps with JohnM
author: JohnM
email: tradexy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
We will use this GitHub Jekyll page to learn and learn DevOps.
DevOps using Microsoft, Azure and other DevOp practices.
Firstly speak to colleagues and users to appreciate DevOps.

# social links
twitter_username: tradexy # DO NOT include the @ character, or else the build will fail!
github_username:  tradexy # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
